Studio fattibilitàmain
Sweleven/Documents pull request #10
Opened 2020-12-16 16:09 UTC by ElMurte

2020-12-20 16:11 UTC, caregnatoedoardo approved these changes

2020-12-20 16:11 UTC, caregnatoedoardo commented on DocumentiInterni/StudioDiFattibilita/src/C6/main.tex
> +\item Essendo Android molto diffuso la documentazione necessaria per realizzare l'applicazione è molto ricca e chiara;
Mettere una virgola dopo "molto diffuso la documentazione", cambiando la frase in "...molto diffuso, la documentazione..."

2020-12-20 16:11 UTC, caregnatoedoardo commented on DocumentiInterni/StudioDiFattibilita/src/C6/main.tex
> +\item Dopo una prima analisi il servizio Gamelift dei vari servizi offerti da Amazon sembra facilitare parecchio lo sviluppo della RGP limitando il numero di microservizzi da sviluppare, partendo dal
A mio avviso, bisognerebbe ristrutturare la frase togliendo i pareri personali ("...nel settore dei servizi cloud abbia creato questo servizio un motivo c'è...")

2020-12-20 16:11 UTC, caregnatoedoardo commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Finalita_del_progetto.tex
> + Il prodotto finale sarà un algoritmo di sincronizzazione e un'interfaccia utilizzabile con i sistemi operativi più diffusi(Linux,Windows, Mac) senza richiedere all'utente finale l'installazione manu
modificare "rapito" in "rapido"

2020-12-20 16:11 UTC, caregnatoedoardo commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Finalita_del_progetto.tex
> + Il prodotto finale sarà un algoritmo di sincronizzazione e un'interfaccia utilizzabile con i sistemi operativi più diffusi(Linux,Windows, Mac) senza richiedere all'utente finale l'installazione manu
Modificare la frase finale "...che permetterà un cambiamento rapito tra l'algoritmo o dell'interfaccia utente" in "...che permetterà un cambiamento rapito dell'algoritmo o dell'interfaccia utente."

2020-12-22 15:34 UTC, Butterneck requested changes

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Studio delle tecnologie e librerie proposte;
Non e' un prerequisito

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Conoscenza funzionamento e protocolli \glo{RFID};
Meh

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item \glo{Java}, \glo{Python} o \glo{Node.js} per lo sviluppo del server back-end;
Java, Python, Node sono strumenti, non tecnologie

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Gestire più stanze, postazioni, personale ed utenti: creare, modificare, eliminare;
Riformulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Sviluppo di un'applicazione mobile per dispositivi con sistema \glo{Android} oppure \glo{iOS} che deve permettere:
Aggiustare la concordanza. Usare sempre lo stesso tempo verbale nei sottopunti

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Le tecnologie coinvolte sono nuove e stimolanti ed offrono diversi sbocchi in ambito professionale;
Le tecnologie non offrono sbocchi. Riormulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il contrasto della pandemia è un tema d'importanza rilevante in questo periodo;
Il contrasto della diffusione?

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il discreto grado di sfida proposto può risultare tuttavia ostico e tradursi anche in questo caso in maggior tempo impiegato per la realizzazione del progetto;
Ripetizione del punto precedente

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il capitolato ha smosso l'interesse di molti gruppi partecipanti, potrebbe quindi essere difficile aggiudicarsi l'appalto;
Cambiare "smosso"

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +Questo capitolato ha attirato subito l'attenzione di molti membri del gruppo. Seppure non di semplice svolgimento, le tecnologie che coinvolge sono stimolanti e di grande interesse perchè molto usate
"in" campo professionale

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Descrizione.tex
> +EmporioLambda mira alla creazione di una piattaforma web serverless di vendita e/o acquisto di beni o servizi che utilizzano internet e il trasferimento di denaro e dati che permettono queste transiz
Riformulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Finalita_del_progetto.tex
> +Lo scopo del progetto è creare un'applicazione web di e-commerce dove i protagonisti saranno i clienti che acquisteranno diversi articoli sia fisici che di tipo servizi e i venditori dove metteranno
Riformulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Tecnologie_interessate.tex
> +\item {\bf DynamoDB:} database non relazionale, orientato a dati valore-chiave e documenti;
Riformulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Criticita_e_fattori_di_rischio.tex
> +\item L'azienda proponente ha sede all'estero, quindi la comunicazione con i referenti sarà meno agevole rispetto ai rapporti con un'azienda che ha sede nel territorio nazionale;
Non credo valga come motivazione

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Conclusioni.tex
> +Nonostante tale capitolato abbia destato particolare interesse all'interno del team di lavoro, sia a livello tecnologico che di competenze curricolari, il gruppo si è mostrato più stimolato verso un
La conclusione non deve fare riferimento al altri capitolati => cambiare conclusione

"diversamente allettante" non e' corretto

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C3/main.tex
> +\subsection{Tecnologie coinvolte}
Si citano strumenti e non tecnologie. Basta riformulare un poco

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C3/main.tex
> +        \item Essere disponibile anche se si verifica un guasto e ripristinabile velocemente
Riformulare

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C3/main.tex
> +Il capitolato lascia molta libertà di implementazione, ma giudando gli studenti con suggetimenti sulle tecnologie da utilizzare.
"Giudando"

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +\begin{itemize}
Si citano strumenti => riformulare un poco

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +\subsection{Prerequisiti e tecnologie coinvolte}
Allineare la struttura di questa sezione alla struttura dell'analoga sezione fatta per il C1

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +\item Il proponente è piuttosto competente e professionale, ha inoltre esposto in modo chiaro i vari vincoli ed i casi d'uso presenti nel capitolato.
"Il proponente è piuttosto competente e professionale" ???

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C5/main.tex
> +\subsection{Informazioni generali}
Manca la sezione "Tecnologie coinvolte"

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C5/main.tex
> +    \item Non è richiesta l'implementazione di algoritmi di ricerca operativa, che complicherebbero di molto l'algoritmo
[...] complicherebbero di molto "lo sviluppo"

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C6/main.tex
> +\item sincronizzazione \glo{UI} tra i giocatori (i giocatori vedono e giocano la stessa partita) ma vedono una sorta di fantasma del \glo{player-character} controllato dagli altri avversari.
"Vedono" ?

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Aspetti_positivi.tex
> +\item uno delle tecnologie interessate è stato oggetto di precedente progetto universitario quindi già conosciuto;
Troppo generico

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Aspetti_positivi.tex
> +\item possibilità di imparare ad utilizzare nuovo linguaggio di programmazione come Python;
Non penso valga come aspetto positivo

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Informazioni_Generali.tex
> +\begin{itemize}
Allineare lo stile del paragrafo al paragrafo analogo del C1

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C2/src/Informazioni_generali.tex
> +\item {\bf Nome:} 	EmporioLambda: piattaforma di e-commerce in stile Serverless;
Allineare lo stile al paragrafo analogo del C1

2020-12-22 15:34 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C6/main.tex
> +Tecnologie coinvolte:
Sono strumenti e non tecnologie

2020-12-22 15:36 UTC, Butterneck commented
Non e' mantenuta coerenza nel modo in cui sono esposti i contenuti.
Fare in modo che tutti i capitolati abbiano le stesse (tutte) sezioni
Mettere i ";" al termine degli elementi negli elenchi puntati

2020-12-30 15:59 UTC, Butterneck requested changes

2020-12-30 15:59 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Competenza nella programmazione e strutturazione di un \glo{server};
I server non si programmano e non si strutturano. Cio' a cui ti riferisci si possono chiamare applicazioni server-side

2021-01-03 16:00 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Competenza nella programmazione e strutturazione di un \glo{server};
-  va bene allora se metto direttamente "Competenza nella programmazione e strutturazione di applicazioni server-side" ?
-  altra domanda: dopo che ho modificato il file vi arriva direttamente una notifica o è meglio che vi scrivo che ho corretto qui sotto i commenti?

2021-01-03 18:29 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Competenza nella programmazione e strutturazione di un \glo{server};
- Molto meglio
- Meglio il commento qui sotto

2021-01-03 21:31 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Competenza nella programmazione e strutturazione di un \glo{server};
ottimo grazie!

2021-01-04 10:26 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\subsection{Descrizione del capitolato}
modificata

2021-01-04 10:28 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Competenza nella programmazione e strutturazione di un \glo{server};
corretto

2021-01-04 10:32 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Gestire più stanze, postazioni, personale ed utenti: creare, modificare, eliminare;
modificato

2021-01-04 10:35 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Sviluppo di un'applicazione mobile per dispositivi con sistema \glo{Android} oppure \glo{iOS} che deve permettere:
aggiustato

2021-01-04 10:36 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Le tecnologie coinvolte sono nuove e stimolanti ed offrono diversi sbocchi in ambito professionale;
corretto

2021-01-04 10:37 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item L'azienda è stata piuttosto chiara e precisa sugli obbiettivi ed i vincoli del progetto;
corretto

2021-01-04 10:37 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il contrasto della pandemia è un tema d'importanza rilevante in questo periodo;
aggiunto

2021-01-04 10:40 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il capitolato ha smosso l'interesse di molti gruppi partecipanti, potrebbe quindi essere difficile aggiudicarsi l'appalto;
cambiato

2021-01-04 10:40 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +Questo capitolato ha attirato subito l'attenzione di molti membri del gruppo. Seppure non di semplice svolgimento, le tecnologie che coinvolge sono stimolanti e di grande interesse perchè molto usate
corretto

2021-01-04 10:43 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\item Il discreto grado di sfida proposto può risultare tuttavia ostico e tradursi anche in questo caso in maggior tempo impiegato per la realizzazione del progetto;
modificato

2021-01-04 10:50 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C1/main.tex
> +\subsection{Descrizione del capitolato}
ho fatto tutte le correzoni insieme nello stesso commit non sapendo che mi avrebbe rimesso tutto insieme qui sotto...fammi sapere se può andare

2021-01-04 10:54 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +\subsection{Prerequisiti e tecnologie coinvolte}
allineato

2021-01-04 10:55 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +\begin{itemize}
modificato

2021-01-04 11:00 UTC, Grigotz commented on DocumentiInterni/StudioDiFattibilita/src/C4/main.tex
> +Seppur abbia degli indubbi aspetti positivi, il capitolato fin da subito non ha attirato l'interesse nella quasi totalità dei membri del team. Pertanto fin da subito non è stato preso particolarmente
corretto

2021-01-05 14:52 UTC, wahad88 commented on DocumentiInterni/StudioDiFattibilita/src/C7/src/Aspetti_positivi.tex
> +\item possibilità di imparare ad utilizzare nuovo linguaggio di programmazione come Python;
Imparare un nuovo linguaggio non è un aspetto positivo? motivo?

2021-01-10 15:51 UTC, merged