Norme progetto/main
Sweleven/Documents pull request #15
Opened 2020-12-30 17:39 UTC by Butterneck

[DOC-2]

2020-12-31 14:16 UTC, ElMurte commented on DocumentiInterni/StudioDiFattibilita/main.tex
>  \section{C6}\label{sec:C6}
come mai c'è questo file ed alcune sezioni relative come C2 e C7?

2020-12-31 14:44 UTC, Butterneck commented on DocumentiInterni/StudioDiFattibilita/main.tex
>  \section{C6}\label{sec:C6}
Perche' @wahad88 ha fatto un po' di casino e a quanto pare ha committato robe in questo branch. Compaio anche io come committer perche' ho fatto un rebase dal main prima di aprire la pull request. Quando andra' fatto il merge bisognera' stare attenti a non includere le cose in questo branch che riguardano lo studio di fattibilita'.

2020-12-31 15:08 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/IntroduzioneENorme.tex
> +\item revisione: il documento è stato interamente prodotto e rimane in attesa di un verificatore, cui compito sarà quello di verificare le informazioni al suo interno ed, eventualmente, di apportare
il verificatore non deve modificare il documento ma lo deve solo segnalare

2020-12-31 15:10 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/IntroduzioneENorme.tex
> +\item revisione: il documento è stato interamente prodotto e rimane in attesa di un verificatore, cui compito sarà quello di verificare le informazioni al suo interno ed, eventualmente, di apportare
Inserire “il” prima di cui compito

2020-12-31 15:12 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/IntroduzioneENorme.tex
> +\item approvazione: il documento ha superato con successo la fase di revisione, ed è pronto per essere caricato nell’apposita sezione nel repository o rilasciato per la consultazione.
sostituire “nel” con del repository

2020-12-31 15:16 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +Ogni documento prodotto dal gruppo {\Gruppo} contiene, all’inizio dello stesso, un indice, cui scopo è quello di esplicitare le parti gerarchiche che compongono il documento in oggetto.
dopo indice togliere , e mettere il

2020-12-31 15:17 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item logo: il logo del gruppo è posizionato in alto a sinistra;
Errore logico: i primi 2 punti dovrebbero essere la descrizione dell’intestazione, è quindi meglio fare una sezione intestazione e una footer per descriverli

2020-12-31 15:17 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/ClassificazioneDeiDocumenti.tex
> +	\item verbali Interni;
i minuscola

2020-12-31 15:19 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/ClassificazioneDeiDocumenti.tex
> +La documentazione esterna è un tipo di documentazione cui divulgazione sarà esterna al gruppo {\Gruppo}. Fanno parte della documentazione esterna i seguenti tipi di documenti:
-un tipo di documentazione LA cui divulgazione (aggiungere LA)
-Specificare a chi è rivolta questa documentazione esterna

2020-12-31 15:21 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/ClassificazioneDeiDocumenti.tex
> +Al momento della redazione del verbale, un membro del gruppo {\Gruppo} sarà scelto, a rotazione, come Redattore dello stesso. Per ogni incontro del gruppo verrà prodotto un verbale ad uso, come speci
-Riformulare: Ad ogni riunione, un membro del gruppo Sweleven …..
-Riformulare: Una volta approvato, di questo non è prevista la possibilità di modifica, in quanto richiederebbe il cambiamento di azioni e/o azioni …...
-La struttura del verbale è qui descritta: riformulare in La struttura del verbale è la seguente

2020-12-31 15:25 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +	dove X,Y e Z indicano la versione del documento;
Mettere spazio dopo X,

2020-12-31 15:32 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +	\item # indicherà un numero intero naturale progressivo, che sarà l’indice dell’immagine;
- \verb|#| sennò il compilatore segnala
- il simbolo #...

2020-12-31 15:35 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +Ogni diagramma uml inserito all’interno della documentazione avrà estensione png. Il programma atto alla creazione dei diagrammi uml sarà starUML
UML maiuscolo dopo diagramma

2020-12-31 15:40 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +ogni documento scritto, prima del suo effettivo completamento e validazione, viene incrementalmente steso in versioni. Ogni versione di un documento è contrassegnata con una nomenclatura prettamente
Riformulare meglio il primo paragrafo
-Un esempio di codica è la seguente: x.y.z, dove le lettere x,y….. (mettere , al posto di.)
-y indica una versione LA cui stesura (mettere LA)
-z indica una versione del documento ancora in fase di stesura. Anche questo INDICE parte…..

2020-12-31 15:41 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +Per la realizzazione del progetto, è stato deciso all’unanimità dal gruppo di utilizzare il sistema di versioning distribuito GitHub. Ogni componente del gruppo, inoltre, potrà utilizzare il software
Semplificazione: è stato deciso dal gruppo

2020-12-31 15:43 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +Come già precedentemente scritto, il gruppo {\Gruppo} ha deciso di utilizzare il software per versioning GitKraken nella versione gratuita, configurandolo tramite repository pubblico presente su GitL
-Github al posto di gitlab

2020-12-31 15:43 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +	\item eseguire il comando di push per aggiornare la copia in locale con le ultime modifiche presenti nel repository su GitLab, eventualmente scegliendo l’apposito branch a seconda del documento da e
-Github al posto di gitlab
-Il primo comando è pull, non push

2020-12-31 15:46 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +In casi eccezionali può succedere che si necessiti la modifica di un file nel repository, ma che un membro del gruppo {\Gruppo} non abbia accesso al programma GitKraken. I comandi e i passi qui sotto
-“Complementari” in “equivalenti”
-Enfatizzare i comandi (grassetto), magari mettere esempio finale completo

2020-12-31 15:47 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +\subsubsection{Utilizzo di Git da CLI}
Valutare se eliminare completamente il paragrafo 3.6.4 o unirlo in 3.6.5 dicendo che se non è disponibile gitkraken si può usare la cli in questi modi:...

2020-12-31 15:48 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +	\item eseguire il comando git pull per sincronizzare il proprio repository locale con quello remoto, scaricando quindi tutte le modifiche effetuate anche da altri collaboratori;
quindi tutte le modifiche effetTuate anche da altri (manca la T)

2020-12-31 16:01 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +	\item Inspection: il verificatore effettuerà una lettura mirata e specifica in alcuni punti specifici dove c’è più probabilità di riscontrare un errore logico.
Riformulare “lettura mirata e specifica in alcuni” in “lettura mirata in alcuni”

2020-12-31 16:02 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +Questi test si effettuano a seguito di una aggiunta o modifica al sistema, verificando la qualità di nuove versione di software scritte. Lo scopo primario è il test di tutte le nuove funzionalità imp
Correggere: verificando la qualità di nuove versioni di software

2020-12-31 16:02 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +\subsubsection{Test di accetazione}
acceTTazione 2 t

2020-12-31 16:04 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +Il loro scopo è quello di ampliare man mano l’unità di codice testata, tramite integrazione di più unità già precedentemente testate, in modo da combinare e testare sempre più parti del codice. Proce
totale è un parolone, riformulare ex. ad almeno 80% del codice prodotto o a quasi la totalità...

2020-12-31 16:05 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +\begin{center} \textbf{T[t]} \end{center}
Mettere entrambe le lettere maiuscole nella nomenclatura

2020-12-31 16:08 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/IntroduzioneENorme.tex
> +\item creazione: il documento viene inizialmente creato, usando un template unico per tutta la documentazione reperibile nei repository del progetto. Successivamente, durante la prima stesura, il cre
-Controllo punteggiatura, spazi di troppo
- e prima della virgola non ha senso riformulare in modo da...

2020-12-31 16:10 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Validazione.tex
> +Le attività da svolgere per validare il prodotto sono di esclusiva responsabilità del Responsabile di Progetto, e sono le seguenti:
Sono un onere esclusivo” al posto di “sono di esclusiva responsabilità”

2020-12-31 16:11 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Validazione.tex
> +	\item identificazione degli obiettivi da validare;
-Il processo di validazione non è spiegato nei dettagli (pull request, modifiche…)
-Spiegare meglio il nostro processo di validazione

(non sono sicuro che vada in questa sezione delle norme)

2020-12-31 16:16 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +\subsubsection{Tabelle}{\Gruppo}
Sweleven ripetuto 2 volte (non so se volevi metterlo nel titolo)

2020-12-31 16:18 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +	\item gli standard utilizzati;{\Gruppo}
Sweleven messo random dopo "utilizzati"

2020-12-31 16:19 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +	\item gli standard utilizzati;{\Gruppo}
Il secondo punto è sbagliato, dovrebbe andare a capo

2020-12-31 16:23 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +\subsubsection{Verifica ortografica}
spostare in sezione 3.5.1 e spiegare meglio cosa si usa ecc. per farlo...

2020-12-31 16:26 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/main.tex
> +La seguente sezione è dedicata alla definizione dei seguenti processi di organizzazione del ciclo di vita del software progettato. I processi vengono suddivisi in quattro sottosezioni secondo lo stan
Rivedere bene la struttura: i titoli senza numero, numeri senza titoli e com’è fatta la divisione in paragrafi, punteggiatura, regole elenchi, spaziatura

2020-12-31 16:27 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +    \item Approvazione,controllo delle versioni e archiviazione
spazio dopo virgola

2020-12-31 16:28 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +\textbf{Assegnazione delle mansioni, pianificazione delle scadenze e stima dei costi}
Spiegare bene gli epic come funzionano e come li usiamo e come li assegniamo (vedi sotto)

2020-12-31 16:29 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +\subsubsection{Definizione degli obiettivi e setup iniziale}
struttura paragrafo non chiara

2020-12-31 16:31 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Per l'assegnazione dei task (con annessa data di scadenza) e per la stima dei costi verrà utilizzato  Atlassian Jira,un software per il monitoraggio di ticket e progetti, il quale permette di assegna
-utilizzato Atlassian Jira,un software: manca spazio dopo la ,
-La spiegazione del funzionamento di jira è meglio metterla nei processi di supporto(creazione del ticket epic,dipendenze,backlog...), lasciando qui solo la nostra gestione dei ticket (livello, assegnazione organizzativa democratica, ecc) e richiamo al paragrafo dei processi di supporto dove viene spiegato in dettaglio il come si fa effettivamente

2020-12-31 16:32 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Tale fase è regolata dalle seguenti attività:
Sistemare suddivisione paragrafi (magari fare elenco puntato/numerato)

2020-12-31 16:33 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Il responsabile di progetto deve assicurarsi che il prodotto software e i piani(con le relative previsioni correlate) soddisfino i requisiti richiesti.
spazio dopo i piani

2020-12-31 16:38 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +\myparagraph{}L'infrastruttura deve essere definita e documentata per coniugarsi con i requisiti del processo, considerando le procedure coinvolte, gli standard, la sistemistica e le tecniche di svil
elim: 2 e alla fine

2020-12-31 16:39 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +La configurazione dell'infrastruttura deve essere pianificata e documentata. I criteri per la scelta della configurazione devono includere le funzionalità a disposizione, le performance, la sicurezza
-L’elenco va in minuscolo?
-Controllo delle versioni,issue tracking: manca lo spazio dopo la virgola

2020-12-31 16:41 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +\textbf{Controllo delle versioni,issue tracking system e memorizzazione remota condivisa}
L’elenco va in minuscolo?
Controllo delle versioni,issue tracking: manca lo spazio dopo la virgola

2020-12-31 16:43 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\subsection{Processo di perfezionamento}
-Manca spazio dopo valutazione
-Rivedere la struttura dei paragrafi

2020-12-31 16:47 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\myparagraph{}\`E necessario stabilire una procedura di valutazione del processo. Essa deve essere sviluppata, documentata e applicata. I risultati delle valutazioni devono essere memorizzati.
-“epic basato tre criteri” manca il “su”
-Manca spazio: (critico,medio,favorevole)
-Uniformare grado di rischio? medio,basso,elevato oppure critico,medio,favorevole ?

2020-12-31 16:48 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\myparagraph{}Il team deve pianificare ed eseguire revisioni periodiche dei processi per assicurarsi che l'adeguatezza ed efficacia dei processi in questione rimanga tale nell'ottica dei risultati de
riformulare: “questione rimanga tale nell'ottica dei risultati” in “questione rimanga buona ai fini dell’obiettivo”

2020-12-31 16:49 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\myparagraph{}I dati memorizzati (valutazioni, dati archiviati e dati tecnici) devono essere conservati e analizzati per poter comprendere eventuali debolezze e punti di forza dei processi svolti. Le
riformulare: “Per indicare dei cambiamenti utili all'interno del modo di operare all'interno del medesimo” cambiare in “per indicare dei cambiamenti nel modo di operare”

2020-12-31 16:50 UTC, ElMurte commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiApprendimento.tex
> +Il processo di apprendimento riguarda include tutte le specifiche per formare e riqualificare il personale. Tale processo si articola nelle tre fasi seguenti:
“riguarda o include” lasciare solo uno dei due

2020-12-31 16:53 UTC, ElMurte requested changes
Processi supporto e organizzativi:
-Dal paragrafo 3.4.5 il documento diventa centrato, bisogna uniformarlo
-Validare con correzione ortografica il testo
-Riassumere alcune frasi un po troppo prolisse ed articolate
I-l processo di validazione non è spiegato nei dettagli (pull request, modifiche…)
-Mettere come glossario(/glo{nome parola}) le cose da glossario (github, gitkraken, jira, CI, ) e aggiungere il termine se manca…(TODO POST processi primari)
-Elenco immagini?
-Controllare cartella verbali, non compila

2021-01-02 14:43 UTC, 10Andrea10 requested changes
Tutti gli accenti dei processi primari sono sbagliati

2021-01-02 14:43 UTC, 10Andrea10 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/ClassificazioneCasiDUso.tex
> +    \item \textbf{Scopo}: scopo del caso d'uso ? specificare meglio;
definire

2021-01-02 14:43 UTC, 10Andrea10 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/main.tex
> +\input{src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Codifica/main.tex}
I sottoparagrafi hanno la numerazione sbagliata

2021-01-02 15:33 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/main.tex
> +\input{src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Codifica/main.tex}
Aggiornati paragraph in subparagraph

2021-01-02 15:33 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/ClassificazioneCasiDUso.tex
> +    \item \textbf{Scopo}: scopo del caso d'uso ? specificare meglio;
Ho tolto l'annotazione. Non e' necessaria ulteriore definizione

2021-01-02 15:37 UTC, Butterneck commented
> Tutti gli accenti dei processi primari sono sbagliati

Vero, pigrizia. Cambiati gli accenti da acuti a gravi, ove necessario

2021-01-02 15:53 UTC, 10Andrea10 requested changes
Non compila più. Hai sbagliato a cambiare gli accenti lasciando delle parentesi aperte

2021-01-02 17:32 UTC, Butterneck commented
> > > Tutti gli accenti dei processi primari sono sbagliati
> > 
> > 
> > Vero, pigrizia. Cambiati gli accenti da acuti a gravi, ove necessario
> 
> Non compila più. Hai sbagliato a cambiare gli accenti lasciando delle parentesi aperte

Devo aver usato sed troppo allegramente, ora dovrebbe essere a posto

2021-01-03 00:25 UTC, 10Andrea10 approved these changes

2021-01-03 10:27 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +In casi eccezionali può succedere che si necessiti la modifica di un file nel repository, ma che un membro del gruppo {\Gruppo} non abbia accesso al programma GitKraken. I comandi e i passi qui sotto
- si necessiti "della modifica" oppure "sia necessaria la modifica"
- eD i passi...sciocchezza non per forza necessaria ma in genere quando la parola dopo "e" inizia con vocale ci sta "ed"

2021-01-03 10:30 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaConfigurazione.tex
> +
potrebbe essere utile evidenziare i comandi da mettere, tipo in grassetto, così si identificano subito senza errori

2021-01-03 10:36 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +Con questo processo, il gruppo {\Gruppo} si pone come obiettivo primario lo sviluppo di software e prodotti di qualità, sia a livello di documentazione sia a livello di codice prodotto. Tramite una s
in pratica stiamo dicendo "faremo tutto per far contento il prof"? XD
per quanto vero, forse ci sta meglio "obiettivi prefissati CON il committente ED IL PROPONENTE"

2021-01-03 10:40 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +	\item ogni prodotto (documentazione e software) passa attraverso delle fasi definite, ed ognuna propedeutica a quella precedente.
se metti la virgola non mettere "ed", se metti "ed" non mettere la virgola

2021-01-03 10:51 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +Il loro scopo è quello di ampliare man mano l’unità di codice testata, tramite integrazione di più unità già precedentemente testate, in modo da combinare e testare sempre più parti del codice. Proce
un po troppe ripetizioni di "testate", "testare", "test"

2021-01-03 10:54 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +Questi test vengono effettuati con la partecipazione del committente, cui compito è quello di verificare il prodotto per garantire il soddisfacimento del cliente. Il superamento di questo test, garan
il superamento di questi (si riferisce AI, plurale...togliere test per evitare ripetizione), garantisce..

2021-01-03 10:59 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/IntroduzioneENorme.tex
> +Per uniformare i documenti che verranno prodotti durante lo sviluppo del software, il gruppo ha scelto di adottare un template \LaTeX{} per velocizzare la stesura degli stessi, riducendo il notevole
spreco di concentrazione E DI TEMPO

2021-01-03 11:02 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +	\item l’header della tabella, avrà sfondo blu e colore di background bianco;
il colore di background non è appunto lo sfondo?

2021-01-03 11:05 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +Tutte le immagini utilizzate durante la stesura della documentazione, dovranno essere collocate in una organizzazione gerarchica all’interno delle cartelle e sottocartelle della documentazione. In pa
collocate SEGUENDO una organizzazione gerarchica

2021-01-03 11:07 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +	\item nomeimmagine indicherà il nome proprio dell’immagine;
nell'esempio sopra hai scritto "nomeimg", metterlo anche qua uguale oppure mettere "nomeimmagine" anche sopra

2021-01-03 11:11 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Strumenti.tex
> +Per la creazione della documentazione del progetto "nomeprogetto", il gruppo {\Gruppo} ha concordato per l’utilizzo del linguaggio di markup \LaTeX{}, con editor desktop TexMaker/TexShop e compilator
\NomeProgetto{} dovrebbe essere impostato, in caso contrario modificare il file Sweleven.sty alla riga 136 aggiungendo "BlockCovid" dentro le graffe

2021-01-03 11:15 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +Ogni documento prodotto che verrà consegnato assieme al software "nomesoftware" verrà realizzato secondo la struttura spiegata nel corso di questa documentazione.
si può togliere "nomesoftware", eventualmente sostituire con \NomeProgetto{}

2021-01-03 11:17 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item gruppo e progetto: il nome del gruppo è visibile immediatamente sotto il logo. In aggiunta, è presente anche la lista dei nomi dei contributori dello specifico documento;
per il nome subito sotto il logo, si intende quello scritto nella parte testuale assieme ai contributori? perchè altrimenti nome e logo sono praticamente una cosa unica

2021-01-03 11:20 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +Ogni documento riporta una sezione denominata con il nome sopracitato, recante una descrizione sommaria sulle modifiche effettuate al documento. Il presente registro è formattato in modalità tabellar
- denominata COME sopracitato
- descrizione sommaria DELLE modifiche

2021-01-03 11:23 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +Ogni documento prodotto dal gruppo {\Gruppo} contiene, all’inizio dello stesso, un indice, cui scopo è quello di esplicitare le parti gerarchiche che compongono il documento in oggetto.
esplicitare LA STRUTTURA E LE GERARCHIE DEL documento in oggetto

2021-01-03 11:24 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +I documenti muniti di figure saranno provvisti di un indice delle figure contenute, con una breve descrizione della stessa ed il numero della pagina dove è collocata.
contenute IN ESSO, con una breve descrizione e la pagina relativa.

2021-01-03 11:29 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item sezione: il nome ed il numero della sezione sono posizionati in centro alla pagina;
inoltre il numero ed il nome...in realtà figurano in alto a destra

2021-01-03 11:30 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item numero pagina: presente in basso a destra, su ogni pagina ad esclusione della prima pagina.
inoltre ci sarebbe anche in basso a sinistra del footer il nome e la versione del documento

2021-01-03 11:34 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Validazione.tex
> +Lo scopo della validazione è accertare che il prodotto finale soddisfi il compito per il quale è stato creato, ovvero che rispetti i vincoli obbligatori del committente. Questo processo quindi restit
attenzione che il committente è il prof. mentre l'azienda è il "proponente"
volendo, utilizzare i comandi \proponente{} e \committenti{} per farli apparire in automatico, se non già impostati basta metterli nel file Sweleven.sty alle righe 128/129

2021-01-03 11:39 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/main.tex
> +La seguente sezione è dedicata alla definizione dei seguenti processi di organizzazione del ciclo di vita del software progettato. I processi vengono suddivisi in quattro sottosezioni secondo lo stan
occhio alle troppe ripetizioni:
- dedicata alla definizione dei (togliere seguenti) processi
- ESSI vengono suddivisi

2021-01-03 11:42 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +\myparagraph{} Una volta stabiliti tali requisiti, il responsabile di progetto deve stabilire la fattibilità del progetto, basandosi sulla documentazione relativa alla disponibilità delle risorse pre
- Offerta maiuscolo è giusto? in caso indicizzare con \glo{}
- spazi tra parentesi e virgole
- può starci bene anche sottoforma di elenco puntato

2021-01-03 11:51 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +
bisogna dare per scontato che chi legge possa non sapere niente di informatica, quindi se si citano nomi propri di strumenti, piattaforme, software, metodi, ecc, meglio presentarli accennando (almeno vagamente) a cosa sono:
es:
- verranno utilizzati GLI STRUMENTI sonarqube ecc..
- CI, qualcuno potrebbe non sapere cosa sia quindi mettere tipo nome completo "Continuous Integration (CI)" o viceversa

2021-01-03 14:23 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Il responsabile di progetto deve investigare, analizzare e risolvere eventuali problemi scoperti durante l'esecuzione del processo. La risoluzione dei problemi può prevedere anche eventuali modifiche
l'impatto DI ciascuna modifica

2021-01-03 14:26 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Il guadagno è calcolato come differenza tra il costo previsto per lo svolgimento dell'attività e il costo effettivo finale associato al completamento dell'attività. Un guadagno positivo indica una sp
- rispetto a quelle assegnate PER il completamento del processo
- spazi prima e dopo le parentesi

2021-01-03 14:32 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione.tex
> +Il progettista ha il compito di supervisionare e gestire le attività di progettazione. A tale figura pertanto vengono associati i documenti di specifica tecnica, definizione di prodotto e piano di qu
buona norma, se si mette l'articolo su un elemento dell'elenco, metterlo su tutti

2021-01-03 14:40 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiApprendimento.tex
> +\end{itemize}
Riformulerei un attimo. Visto che comunque noi optiamo per un apprendimento principalmente autonomo, si potrebbe solo accennare in maniera molto sintetica alle norme consigliate per il piano di apprendimento..oppure addirittura togliere proprio tutto e lasciare solo la parte dalla riga 24 in poi.

2021-01-03 14:46 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> + Per la realizzazione di videoconferenze telematiche, verrà utilizzato l'apposito server privato "SWEG11" sulla piattaforma di VoIP Discord.
modificare SWEG11 con \Gruppo{}, già impostato nel file Sweleven.sty..se non è impostato basta metterlo, alla riga 89 dentro le graffe

2021-01-03 14:48 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +
per rendere più sintetico il tutto si potrebbe soltato trasformare ognuno di questi elementi dell'elenco puntato in un \subsubsection e scrivere direttamente sotto ognuno le relative info principali

2021-01-03 14:50 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +/*Da stabilire con l'azienda ed eventualmente il professore in seguito all'assegnazione del capitolato.*/
aggiornare con le modalità finora concordate

2021-01-03 14:51 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiInfrastruttura.tex
> +\myparagraph{}L'infrastruttura deve essere mantenuta, monitorata e modificata se necessario per poter mantenere il requisito di appagamento dei requisiti del processo. Ciò deve dunque includere una d
ripetizione requisito/requisiti

2021-01-03 14:53 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +
anche qui si potrebbe fare direttamente un subsubsection per ognuno, con relativo approfondimento direttamente sotto

2021-01-03 14:54 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +Il processo di perfezionamento riguarda l'istituzione, la valutazione,il controllo e il miglioramento del ciclo di vita del software. Il processo segue le seguenti fasi:
spazio dopo virgola

2021-01-03 15:06 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\myparagraph{}Il team deve pianificare ed eseguire revisioni periodiche dei processi per assicurarsi che l'adeguatezza ed efficacia dei processi in questione rimanga tale nell'ottica dei risultati de
spazi dopo virgole spesso mancanti

2021-01-03 15:07 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/src/ProcessoDiPerfezionamento.tex
> +\myparagraph{}Il team di sviluppo deve apportare dei miglioramenti ai propri processi qualora si rivelasse necessario secondo i risultati della valutazione del processo. La documentazione relativa al
tante ripetizioni della parola "processi"

2021-01-03 15:07 UTC, 10Andrea10 requested changes

2021-01-03 15:07 UTC, 10Andrea10 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +	\item per facilitare la lettura tra più righe, si differenzieranno le righe con indice pari da quelle dispari, alternando ciclicamente il colore bianco e grigio;
```suggestion
	\item per facilitare la lettura tra più righe, si differenzieranno le righe con indice pari da quelle dispari, alternando ciclicamente il colore grigio chiaro e il colore grigio;
```

2021-01-03 15:08 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Inizializzazione.tex
> +Al fine di valutare quale Capitolato sia il pi\`{u} adatto alle conoscenze alle attitudini dei componenti del gruppo Sweleven, gli analisti preposti devono effettuare una valutazione di tutti i Capit
alle conoscenze ED alle attitudini

2021-01-03 15:17 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Strumenti.tex
> +Descrizione di Jira
??

2021-01-03 15:20 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
sembra ci si stia riferendo l Piano di Progetto, si potrebbe semplicemente aggiungere tra parentesi un "vedasi PdP" o una cosa del genere

2021-01-03 15:21 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +% Ricontrollare con standard ISO
i commenti son rimasti da prima o sono ancora validi? in caso sistemare

2021-01-03 15:22 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item definire degli standard di qualit\`{a} che il fornitore intende soddisfare, e, di conseguenza, dei processi che facciano in modo che tutto il materiale prodotto dal fornitore, in qualunque
togliere virgola : "soddisfare e, di conseguenza"

2021-01-03 15:32 UTC, 10Andrea10 requested changes

2021-01-03 15:32 UTC, 10Andrea10 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +		\end{itemize}
Manca un ID incrementale per identificare il test esatto.

```suggestion
\begin{center} \textbf{T[t][x]} \end{center}
Dove:
\begin{itemize}
	\item T è una keyword statica per identificare appunto un “Test”
	\item t identifica il tipo di test, che può essere:
		\begin{itemize}
			\item U: test di unità;
			\item  I: test di integrazione;
			\item S: test di sistema;
			\item R: test di regressione;
			\item A: test di accettazione.
		\end{itemize}
	\item x è l'ID univoco e prograssivo utile per identificare il test
```

2021-01-03 15:40 UTC, 10Andrea10 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/GestioneDellaQualita.tex
> +
Forse è meglio indicare anche se i test previsti sono stati implementati o no, indicando un campo Esito per ogni test, non dando per scontato che tutti i test inseriti nel PdQ vengano implementati.

2021-01-03 15:45 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/scopo.tex
> +    \item funzionalita' e requisiti concordati con il proponente?
sistemare con indicazioni definitive, alla fine possiamo decidere anche noi, a seconda di quanto sia opportuno ai fini del nostro lavoro, se vogliamo mettere o meno qualcosa

2021-01-03 15:48 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Codifica/src/scopo.tex
> +Il gruppo \Gruppo{} ha deciso di adottare precisi stili e le modalit\`{a} di codifica al fine di:
correggere in: "adottare DEI precisi stili e modalità di codifica" oppure  "adottare precisi stili ALLE modalità di codifica", a seconda del senso che si vuole dare alla frase

2021-01-03 15:50 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Progettazione/src/scopo.tex
> +L'attivit\`{a} di progettazione avviene al termine dell'attivit\`{a} di analisi dei requisiti e deve concludersi prima dell'ativit\`{a} di codifica.
per sisntetizzare il doc si può unificare in un'unica frase

2021-01-03 16:52 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiOrganizzativi/main.tex
> +\input{src/ProcessiOrganizzativi/src/ProcessoDiAmministrazione}
Manca l'estensione .tex a tutti gli input

2021-01-03 17:10 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/main.tex
> +\end{document}
eliminare
\end{document} e aggiungere l'estensione .tex alla fine dell'input per esempio Strumenti.tex

2021-01-03 17:25 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
il quale il fornitore "pianificherà"

2021-01-03 17:27 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +requisiti concordati. A tale fine \'{e} quindi necessario:
l'accento corretto sarebbe "è" invece compilando diventa "é"

2021-01-03 17:34 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/PreparazioneDellaRisposta.tex
> +Il resposabile % E' il responsabile che la deve fare?
il "responsabile"

2021-01-03 17:45 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Pianificazione.tex
> +    \item al fine di stimare i costi previsti, viene calcolato un preventivo, attraverso l'attribuzione di un costo ad ogni attivit\`{a} . Al termine di ogni fase progettuale vengono redatti dei cons
togliere lo spazio dopo "ogni attività" prima del punto

2021-01-03 17:47 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Pianificazione.tex
> +I \verificatori{} devono redigere il documento \PdQv{} in cui sono descritti i processi di verifica e le attivit\`{a} che vengono intraprese al fine di garantire la qualit\`{a} del materiale prodotto
Aggiungere la , dopo "In particolare"

2021-01-03 17:48 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Pianificazione.tex
> +    \item valutazioni per il miglioramento
Mettere i ; alla fine di ogni item e il . nell'ultimo item

2021-01-03 18:18 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Codifica/src/scopo.tex
> +Il gruppo \Gruppo{} ha deciso di adottare precisi stili e le modalit\`{a} di codifica al fine di:
"Il complemento oggetto non necessita preposizioni"
"Il complemento oggetto non necessita di preposizioni"

E' corretto cosi :)

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Pianificazione.tex
> +    \item valutazioni per il miglioramento
aggiunti

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Pianificazione.tex
> +    \item al fine di stimare i costi previsti, viene calcolato un preventivo, attraverso l'attribuzione di un costo ad ogni attivit\`{a} . Al termine di ogni fase progettuale vengono redatti dei cons
rimosso

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/PreparazioneDellaRisposta.tex
> +Il resposabile % E' il responsabile che la deve fare?
corretto

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +requisiti concordati. A tale fine \'{e} quindi necessario:
giusto

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
corretto

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Progettazione/src/scopo.tex
> +L'attivit\`{a} di progettazione avviene al termine dell'attivit\`{a} di analisi dei requisiti e deve concludersi prima dell'ativit\`{a} di codifica.
Sintetizzato

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item definire degli standard di qualit\`{a} che il fornitore intende soddisfare, e, di conseguenza, dei processi che facciano in modo che tutto il materiale prodotto dal fornitore, in qualunque
La virgola e' corretta

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +% Ricontrollare con standard ISO
Rimossi

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
Ci si riferisce al PdP, il documento serve appunto a normarne la stesura

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Strumenti.tex
> +Descrizione di Jira
Il file non e' incluso nella compilazione. E' un refuso

2021-01-03 18:27 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Inizializzazione.tex
> +Al fine di valutare quale Capitolato sia il pi\`{u} adatto alle conoscenze alle attitudini dei componenti del gruppo Sweleven, gli analisti preposti devono effettuare una valutazione di tutti i Capit
- corretto
- corretto
- e' corretto con la virgola

2021-01-03 18:28 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/scopo.tex
> +    \item funzionalita' e requisiti concordati con il proponente?
messi opzionali

2021-01-03 20:52 UTC, caregnatoedoardo commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item gruppo e progetto: il nome del gruppo è visibile immediatamente sotto il logo. In aggiunta, è presente anche la lista dei nomi dei contributori dello specifico documento;
Questa cosa l'avevo scritta ancora prima di definire un logo xD
Se scrivo che il nome del gruppo è visibile all'interno del logo, va bene lo stesso?

2021-01-04 09:49 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item gruppo e progetto: il nome del gruppo è visibile immediatamente sotto il logo. In aggiunta, è presente anche la lista dei nomi dei contributori dello specifico documento;
mah si, si potrebbe semplicemente aggiungere nel primo item "il logo del gruppo COMPRENSIVO DEL NOME è visibile..." e nel secondo togliere la prima frase e scrivere solo della lista dei contributori ecc

2021-01-04 09:56 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/Attivita/src/Inizializzazione.tex
> +Al fine di valutare quale Capitolato sia il pi\`{u} adatto alle conoscenze alle attitudini dei componenti del gruppo Sweleven, gli analisti preposti devono effettuare una valutazione di tutti i Capit
solitamente prima dell'ultimo elemento di una lista, quando metti  "e" non c'è bisogno della virgola..però vabbè son minuzie, forse è corretto anche così

2021-01-04 10:03 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
se "secondo il quale" è riferito all'organizzazione va messo "secondo LA quale",  perchè femminile

2021-01-04 10:09 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item definire degli standard di qualit\`{a} che il fornitore intende soddisfare, e, di conseguenza, dei processi che facciano in modo che tutto il materiale prodotto dal fornitore, in qualunque
quando si mette la "e" in genere non serve la virgola prima perchè, come in questo caso, assolvono praticamente alla stessa funzione di pausa o congiunzione, quindi diventa ridondante. Inoltre mettere troppe virgole mina alla leggibilità (spesso colpevole anch'io di queso XD) rendendo il periodo troppo lungo e di conseguenza meno chiaro e scorrevole.

2021-01-04 10:15 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Codifica/src/scopo.tex
> +Il gruppo \Gruppo{} ha deciso di adottare precisi stili e le modalit\`{a} di codifica al fine di:
si hai ragione, DEI non è per forza necessario..più che altro non capivo se "precisi stili" era riferito in generale oppure alle modalità di codifica

2021-01-04 15:47 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/ClassificazioneCasiDUso.tex
> +    \item \textbf{Postcondizioni}: condizioni che devono essere verificarsi alla conclusione degli eventi descritti;
che devono essere "verificati"

2021-01-04 15:48 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/ClassificazioneCasiDUso.tex
> +    \item \textbf{Inclusioni}: indicazione delle inclusioni \emph{(se presenti)}
Correggere la punteggiatura alla fine dei paragrafi

2021-01-04 15:56 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Progettazione/src/scopo.tex
> +L'attivit\`{a} di progettazione ha lo scopo di definire l'architettura logica del prodotto da sviluppare, viene inizializzata al termine dell'attivit\`{a} di analisi dei requisiti e conclusa prima de
conclusa prima "dell'attività" di codifica.

2021-01-04 15:59 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Progettazione/src/TechnologyBaseline.tex
> +    \item \textbf{Tracciamento delle componenti}: associazione tra requisiti e componenti che li soddisfano.
; alla fine del paragrafo

2021-01-04 16:40 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Strumenti.tex
> +
Aggiungere Draw.io per la creazione dei diagrammi

2021-01-04 22:51 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Fornitura/src/scopo.tex
> +    \item redigere un documento che descriva in modo dettagliato l'organizzazione secondo il quale il fornitore pinificher\`{a} le attivit\`{a} durante tutte le fasi del progetto; % RIVEDERE QUESTO I
corretto

2021-01-04 22:52 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/AnalisiDeiRequisiti/src/ClassificazioneCasiDUso.tex
> +    \item \textbf{Inclusioni}: indicazione delle inclusioni \emph{(se presenti)}
corretto

2021-01-04 22:53 UTC, Butterneck commented on DocumentiInterni/NormeDiProgetto/src/ProcessiPrimari/src/Sviluppo/src/Attivita/src/Progettazione/src/scopo.tex
> +L'attivit\`{a} di progettazione ha lo scopo di definire l'architettura logica del prodotto da sviluppare, viene inizializzata al termine dell'attivit\`{a} di analisi dei requisiti e conclusa prima de
corretto

2021-01-05 10:02 UTC, caregnatoedoardo commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/Strumenti.tex
> +
Aggiunto nella sezione Norme Tipografiche -> "Diagrammi UML"

2021-01-05 10:18 UTC, caregnatoedoardo commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item numero pagina: presente in basso a destra, su ogni pagina ad esclusione della prima pagina.
Thanks :D
Scusa per il lieve casino, ma i processi di supporto li avevo fatti basandomi anche su altre documentazioni, prima della costruzione del nostro template xD

2021-01-05 10:59 UTC, Grigotz commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/StrutturaDellaDocumentazione.tex
> +	\item numero pagina: presente in basso a destra, su ogni pagina ad esclusione della prima pagina.
nessun problema era giusto per avvisare :)

2021-01-05 16:29 UTC, 10Andrea10 approved these changes

2021-01-06 01:16 UTC, wahad88 commented on DocumentiInterni/NormeDiProgetto/src/ProcessiDiSupporto/src/NormeTipografiche.tex
> +    \centering
Togliete \centering altrimenti sballa tutto il resto del template ed inserirlo prima del \textbf{Header 1} su tutti gli Header per esempio \centering\textbf{Header 1}

2021-01-10 16:04 UTC, merged